# Get the HPS model to run
- get the inputs correct
- run through all steps
- get an accuracy estimate

In [1]:
import os
import sys
sys.path.append('/home/surchs/git/Proteus/')
import proteus.predic as pp

import numpy as np
import pandas as pd
import nibabel as nib
import sklearn as skl
import scipy.io as sio
from sklearn.model_selection import StratifiedKFold

In [2]:
# Paths
root_p = '/home/surchs/sim_big/PROJECT/abide_hps/'
# Pheno
sample_p = os.path.join(root_p, 'pheno', 'psm_abide1.csv')
# Data
resid_ct_p = os.path.join(root_p, 'residual', 'ct_30mm_residual_psm.npy')
resid_fc_p = os.path.join(root_p, 'residual', 'sd_30mm_residual_psm.npy')
mask_p = os.path.join(root_p, 'mask', 'MIST_mask.nii.gz')
subtype_fc_p = os.path.join(root_p, 'subtypes', 'subtypes_fc.npz')
subtype_ct_p = os.path.join(root_p, 'subtypes', 'subtypes_ct.npz')

In [3]:
# Load data
sample = pd.read_csv(sample_p)
s_fc = np.load(subtype_fc_p)
s_ct = np.load(subtype_ct_p)

In [29]:
# Reshape FC to add to the table
fc_weights = np.reshape(s_fc['weights'], (370, 5*20))
fc_cols = ['n{}_s{}'.format(nid+1, sid+1) for sid in range(5) for nid in range(20)]
# Same for CT
ct_weights = s_ct['weights']

In [30]:
ct_weights.shape

(370, 5)

In [4]:
s_fc.keys()

['order', 'part', 'weights', 'subtypes', 'dist']

In [5]:
s_fc['weights'].shape

(370, 5, 20)

In [27]:
s_ct['weights'].shape

(370, 5)

In [18]:
s_fc['weights'].shape

(370, 5, 20)

In [21]:
s_fc['weights'][:10, 2, 9]

array([-0.07190089, -0.00275686,  0.01689983,  0.12003633, -0.14754443,
       -0.04186613,  0.1617764 , -0.29200462,  0.0192163 , -0.18488302])

In [25]:
fc_cols.index('n10_s3')

49

In [26]:
fc_weights[:10, 49]

array([-0.07190089, -0.00275686,  0.01689983,  0.12003633, -0.14754443,
       -0.04186613,  0.1617764 , -0.29200462,  0.0192163 , -0.18488302])

In [13]:
fc_weights[:10, 1]

array([-0.03740277, -0.23201091,  0.28162358,  0.20842898, -0.14411448,
       -0.04910096, -0.00163657, -0.00466562,  0.42742324, -0.17013592])

In [8]:
w = s_fc['weights']

In [7]:
w.shape

(370, 5, 20)

In [33]:
fc_weights[:10, 6]

array([ 0.06344403,  0.08203333,  0.1300488 , -0.35      ,  0.00798571,
        0.1411863 , -0.02476743,  0.01724024, -0.07803099,  0.12310752])

In [22]:
fc_cols.index('n3_s2')

11

In [15]:
fc_weights.shape

(370, 100)

AttributeError: 'NpzFile' object has no attribute 'shape'

In [ ]:
# Build features
x_ = sample

In [6]:
scaler = skl.preprocessing.StandardScaler()

In [ ]:
skf = StratifiedKFold(n_splits=3)


In [ ]:
skl.preprocessing

In [4]:
pt.predic

AttributeError: module 'Proteus' has no attribute 'predic'

In [ ]:
import pandas as pd
import scipy.io
from os import listdir
from sklearn.utils import shuffle
from sklearn import preprocessing
from nilearn import plotting
#from proteus.io import util
from proteus.visu import sbp_visu

import glob,os
import nibabel as nib


import pickle
from proteus.predic import high_confidence
import numpy as np
import pandas as pd
from proteus.predic import prediction
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold

from sklearn import metrics

import matplotlib.pyplot as plt
from matplotlib import cm
import seaborn as sns

import statsmodels.formula.api as smf
import statsmodels.api as sm
from statsmodels.stats.multicomp import pairwise_tukeyhsd

from copy import deepcopy